// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'fr'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * Notes Bibliques
	 */
	'Notes Bibliques': string
	/**
	 * La Bible
	 */
	Bible: string
	/**
	 * Ancien Testament
	 */
	OT: string
	/**
	 * Nouveau Testament
	 */
	NT: string
	/**
	 * Genèse
	 */
	Gen: string
	/**
	 * Exode
	 */
	Exod: string
	/**
	 * Lévitique
	 */
	Lev: string
	/**
	 * Nombres
	 */
	Num: string
	/**
	 * Deutéronome
	 */
	Deut: string
	/**
	 * Josué
	 */
	Josh: string
	/**
	 * Juges
	 */
	Judg: string
	/**
	 * Ruth
	 */
	Ruth: string
	/**
	 * 1 Samuel
	 */
	'1Sam': string
	/**
	 * 2 Samuel
	 */
	'2Sam': string
	/**
	 * 1 Rois
	 */
	'1Kgs': string
	/**
	 * 2 Rois
	 */
	'2Kgs': string
	/**
	 * 1 Chroniques
	 */
	'1Chr': string
	/**
	 * 2 Chroniques
	 */
	'2Chr': string
	/**
	 * Esdras
	 */
	Ezra: string
	/**
	 * Néhémie
	 */
	Neh: string
	/**
	 * Esther
	 */
	Esth: string
	/**
	 * Job
	 */
	Job: string
	/**
	 * Psaumes
	 */
	Ps: string
	/**
	 * Proverbes
	 */
	Prov: string
	/**
	 * Ecclésiaste
	 */
	Eccl: string
	/**
	 * Cantique des Cantiques
	 */
	Song: string
	/**
	 * Esaie
	 */
	Isa: string
	/**
	 * Jérémie
	 */
	Jer: string
	/**
	 * Lamentations de Jérémie
	 */
	Lam: string
	/**
	 * Ezechiel
	 */
	Ezek: string
	/**
	 * Daniel
	 */
	Dan: string
	/**
	 * Osée
	 */
	Hos: string
	/**
	 * Joël
	 */
	Joel: string
	/**
	 * Amos
	 */
	Amos: string
	/**
	 * Abdias
	 */
	Obad: string
	/**
	 * Jonas
	 */
	Jonah: string
	/**
	 * Michée
	 */
	Mic: string
	/**
	 * Nahum
	 */
	Nah: string
	/**
	 * Habacuc
	 */
	Hab: string
	/**
	 * Sophonie
	 */
	Zeph: string
	/**
	 * Aggée
	 */
	Hag: string
	/**
	 * Zacharie
	 */
	Zech: string
	/**
	 * Malachie
	 */
	Mal: string
	/**
	 * Matthieu
	 */
	Matt: string
	/**
	 * Marc
	 */
	Mark: string
	/**
	 * Luc
	 */
	Luke: string
	/**
	 * Jean
	 */
	John: string
	/**
	 * Actes des Apôtres
	 */
	Acts: string
	/**
	 * Romains
	 */
	Rom: string
	/**
	 * 1 Corinthiens
	 */
	'1Cor': string
	/**
	 * 2 Corinthiens
	 */
	'2Cor': string
	/**
	 * Galates
	 */
	Gal: string
	/**
	 * Ephésiens
	 */
	Eph: string
	/**
	 * Philippiens
	 */
	Phil: string
	/**
	 * Colossiens
	 */
	Col: string
	/**
	 * 1 Thessaloniciens
	 */
	'1Thess': string
	/**
	 * 2 Thessaloniciens
	 */
	'2Thess': string
	/**
	 * 1 Timothée
	 */
	'1Tim': string
	/**
	 * 2 Timothée
	 */
	'2Tim': string
	/**
	 * Tite
	 */
	Titus: string
	/**
	 * Philémon
	 */
	Phlm: string
	/**
	 * Hébreux
	 */
	Heb: string
	/**
	 * Jacques
	 */
	Jas: string
	/**
	 * 1 Pierre
	 */
	'1Pet': string
	/**
	 * 2 Pierre
	 */
	'2Pet': string
	/**
	 * 1 Jean
	 */
	'1John': string
	/**
	 * 2 Jean
	 */
	'2John': string
	/**
	 * 3 Jean
	 */
	'3John': string
	/**
	 * Jude
	 */
	Jude: string
	/**
	 * Apocalypse
	 */
	Rev: string
}

export type TranslationFunctions = {
	/**
	 * Notes Bibliques
	 */
	'Notes Bibliques': () => LocalizedString
	/**
	 * La Bible
	 */
	Bible: () => LocalizedString
	/**
	 * Ancien Testament
	 */
	OT: () => LocalizedString
	/**
	 * Nouveau Testament
	 */
	NT: () => LocalizedString
	/**
	 * Genèse
	 */
	Gen: () => LocalizedString
	/**
	 * Exode
	 */
	Exod: () => LocalizedString
	/**
	 * Lévitique
	 */
	Lev: () => LocalizedString
	/**
	 * Nombres
	 */
	Num: () => LocalizedString
	/**
	 * Deutéronome
	 */
	Deut: () => LocalizedString
	/**
	 * Josué
	 */
	Josh: () => LocalizedString
	/**
	 * Juges
	 */
	Judg: () => LocalizedString
	/**
	 * Ruth
	 */
	Ruth: () => LocalizedString
	/**
	 * 1 Samuel
	 */
	'1Sam': () => LocalizedString
	/**
	 * 2 Samuel
	 */
	'2Sam': () => LocalizedString
	/**
	 * 1 Rois
	 */
	'1Kgs': () => LocalizedString
	/**
	 * 2 Rois
	 */
	'2Kgs': () => LocalizedString
	/**
	 * 1 Chroniques
	 */
	'1Chr': () => LocalizedString
	/**
	 * 2 Chroniques
	 */
	'2Chr': () => LocalizedString
	/**
	 * Esdras
	 */
	Ezra: () => LocalizedString
	/**
	 * Néhémie
	 */
	Neh: () => LocalizedString
	/**
	 * Esther
	 */
	Esth: () => LocalizedString
	/**
	 * Job
	 */
	Job: () => LocalizedString
	/**
	 * Psaumes
	 */
	Ps: () => LocalizedString
	/**
	 * Proverbes
	 */
	Prov: () => LocalizedString
	/**
	 * Ecclésiaste
	 */
	Eccl: () => LocalizedString
	/**
	 * Cantique des Cantiques
	 */
	Song: () => LocalizedString
	/**
	 * Esaie
	 */
	Isa: () => LocalizedString
	/**
	 * Jérémie
	 */
	Jer: () => LocalizedString
	/**
	 * Lamentations de Jérémie
	 */
	Lam: () => LocalizedString
	/**
	 * Ezechiel
	 */
	Ezek: () => LocalizedString
	/**
	 * Daniel
	 */
	Dan: () => LocalizedString
	/**
	 * Osée
	 */
	Hos: () => LocalizedString
	/**
	 * Joël
	 */
	Joel: () => LocalizedString
	/**
	 * Amos
	 */
	Amos: () => LocalizedString
	/**
	 * Abdias
	 */
	Obad: () => LocalizedString
	/**
	 * Jonas
	 */
	Jonah: () => LocalizedString
	/**
	 * Michée
	 */
	Mic: () => LocalizedString
	/**
	 * Nahum
	 */
	Nah: () => LocalizedString
	/**
	 * Habacuc
	 */
	Hab: () => LocalizedString
	/**
	 * Sophonie
	 */
	Zeph: () => LocalizedString
	/**
	 * Aggée
	 */
	Hag: () => LocalizedString
	/**
	 * Zacharie
	 */
	Zech: () => LocalizedString
	/**
	 * Malachie
	 */
	Mal: () => LocalizedString
	/**
	 * Matthieu
	 */
	Matt: () => LocalizedString
	/**
	 * Marc
	 */
	Mark: () => LocalizedString
	/**
	 * Luc
	 */
	Luke: () => LocalizedString
	/**
	 * Jean
	 */
	John: () => LocalizedString
	/**
	 * Actes des Apôtres
	 */
	Acts: () => LocalizedString
	/**
	 * Romains
	 */
	Rom: () => LocalizedString
	/**
	 * 1 Corinthiens
	 */
	'1Cor': () => LocalizedString
	/**
	 * 2 Corinthiens
	 */
	'2Cor': () => LocalizedString
	/**
	 * Galates
	 */
	Gal: () => LocalizedString
	/**
	 * Ephésiens
	 */
	Eph: () => LocalizedString
	/**
	 * Philippiens
	 */
	Phil: () => LocalizedString
	/**
	 * Colossiens
	 */
	Col: () => LocalizedString
	/**
	 * 1 Thessaloniciens
	 */
	'1Thess': () => LocalizedString
	/**
	 * 2 Thessaloniciens
	 */
	'2Thess': () => LocalizedString
	/**
	 * 1 Timothée
	 */
	'1Tim': () => LocalizedString
	/**
	 * 2 Timothée
	 */
	'2Tim': () => LocalizedString
	/**
	 * Tite
	 */
	Titus: () => LocalizedString
	/**
	 * Philémon
	 */
	Phlm: () => LocalizedString
	/**
	 * Hébreux
	 */
	Heb: () => LocalizedString
	/**
	 * Jacques
	 */
	Jas: () => LocalizedString
	/**
	 * 1 Pierre
	 */
	'1Pet': () => LocalizedString
	/**
	 * 2 Pierre
	 */
	'2Pet': () => LocalizedString
	/**
	 * 1 Jean
	 */
	'1John': () => LocalizedString
	/**
	 * 2 Jean
	 */
	'2John': () => LocalizedString
	/**
	 * 3 Jean
	 */
	'3John': () => LocalizedString
	/**
	 * Jude
	 */
	Jude: () => LocalizedString
	/**
	 * Apocalypse
	 */
	Rev: () => LocalizedString
}

export type Formatters = {}
