const hierarchy = {
    type: "full-bible",
    label: "La Bible",
    elements: {
        OT: {
            label: "Ancien Testament",
            type: "section",
            elements: {
                Gen: {
                    label: "Genèse",
                    type: "book",
                },
                Exod: { label: "Exode", type: "book" },
                Lev: { label: "Lévitique", type: "book" },
                Num: { label: "Nombres", type: "book" },
                Deut: { label: "Deutéronome", type: "book" },
                Josh: { label: "Josué", type: "book" },
                Judg: { label: "Juges", type: "book" },
                Ruth: { label: "Ruth", type: "book" },
                "1Sam": { label: "1 Samuel", type: "book" },
                "2Sam": { label: "2 Samuel", type: "book" },
                "1Kgs": { label: "1 Rois", type: "book" },
                "2Kgs": { label: "2 Rois", type: "book" },
                "1Chr": { label: "1 Chroniques", type: "book" },
                "2Chr": { label: "2 Chroniques", type: "book" },
                Ezra: { label: "Esdras", type: "book" },
                Neh: { label: "Néhémie", type: "book" },
                Esth: { label: "Esther", type: "book" },
                Job: { label: "Job", type: "book" },
                Ps: { label: "Psaumes", type: "book" },
                Prov: { label: "Proverbes", type: "book" },
                Eccl: { label: "Ecclésiaste", type: "book" },
                Song: { label: "Cantique des Cantiques", type: "book" },
                Isa: { label: "Esaie", type: "book" },
                Jer: { label: "Jérémie", type: "book" },
                Lam: { label: "Lamentations de Jérémie", type: "book" },
                Ezek: { label: "Ezechiel", type: "book" },
                Dan: { label: "Daniel", type: "book" },
                Hos: { label: "Osée", type: "book" },
                Joel: { label: "Joël", type: "book" },
                Amos: { label: "Amos", type: "book" },
                Obad: { label: "Abdias", type: "book" },
                Jonah: { label: "Jonas", type: "book" },
                Mic: { label: "Michée", type: "book" },
                Nah: { label: "Nahum", type: "book" },
                Hab: { label: "Habacuc", type: "book" },
                Zeph: { label: "Sophonie", type: "book" },
                Hag: { label: "Aggée", type: "book" },
                Zech: { label: "Zacharie", type: "book" },
                Mal: { label: "Malachie", type: "book" },
            },
        },
        NT: {
            label: "Nouveau Testament",
            type: "section",
            elements: {
                Matt: { label: "Matthieu", type: "book" },
                Mark: { label: "Marc", type: "book" },
                Luke: { label: "Luc", type: "book" },
                John: { label: "Jean", type: "book" },
                Acts: { label: "Actes des Apôtres", type: "book" },
                Rom: { label: "Romains", type: "book" },
                "1Cor": { label: "1 Corinthiens", type: "book" },
                "2Cor": { label: "2 Corinthiens", type: "book" },
                Gal: { label: "Galates", type: "book" },
                Eph: { label: "Ephésiens", type: "book" },
                Phil: { label: "Philippiens", type: "book" },
                Col: { label: "Colossiens", type: "book" },
                "1Thess": { label: "1 Thessaloniciens", type: "book" },
                "2Thess": { label: "2 Thessaloniciens", type: "book" },
                "1Tim": { label: "1 Timothée", type: "book" },
                "2Tim": { label: "2 Timothée", type: "book" },
                Titus: { label: "Tite", type: "book" },
                Phlm: { label: "Philémon", type: "book" },
                Heb: { label: "Hébreux", type: "book" },
                Jas: { label: "Jacques", type: "book" },
                "1Pet": { label: "1 Pierre", type: "book" },
                "2Pet": { label: "2 Pierre", type: "book" },
                "1John": { label: "1 Jean", type: "book" },
                "2John": { label: "2 Jean", type: "book" },
                "3John": { label: "3 Jean", type: "book" },
                Jude: { label: "Jude", type: "book" },
                Rev: { label: "Apocalypse", type: "book" },
            },
        },
    },
};

export { hierarchy };
